import type { Metadata } from "next";
import { Roboto, Poppins } from "next/font/google";
import "./globals.css";


const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${poppins.variable} bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
